spring:
  application:
    name: demo-jwt

  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    initialization-mode: always
    #always: 데이터 소스가 항상 초기화됩니다.
    #embedded: 데이터 소스가 임베디드 데이터베이스인 경우에만 초기화됩니다.
    #never: 데이터 소스를 절대 초기화하지 않습니다.
    #Default: embedded

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      #애플리케이션이 시작될 때 데이터베이스 스키마를 삭제하고 새로 생성합니다. 기존 데이터는 모두 삭제됩니다.
      #Options: none(db 변화없음), validate(운영시스템 안정성 체크), update, create, create-drop
      show-sql: true
      #Hibernate가 실행하는 모든 SQL 쿼리를 콘솔에 출력합니다.
      #Default: false
      format-sql: true
      #출력되는 SQL 쿼리를 보기 좋게 포맷팅합니다.
      #Default: false
    defer-datasource-initialization: true
      #JPA 데이터 소스 초기화를 지연시켜 JPA 스키마가 생성된 후 SQL 스크립트를 실행합니다.
      #src/main/resources/data.sql 방식으로 데이터 초기 적재를 하려면 true 필수
      #Default: false
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework: TRACE
      springframework.security: TRACE
